name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle --deployment
          gem install --no-document rspec:'~>3.0'
          gem install --no-document kimurai
          gem install --no-document colorize
<<<<<<< HEAD
          gem install --no-document selenium-webdriver

||||||| merged common ancestors
=======

          gem 'chromedriver-helper'
          gem "selenium-webdriver"

>>>>>>> 6ea56a96614219cb86813e4ba47d07d89b45f843
      - name: RSpec Report
        run: rspec --force-color --format documentation